name: testing cache

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-cache-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as it uses the current rustc version as its cache key
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: install webkit2gtk (ubuntu only)
        run: sudo apt-get install -y webkit2gtk-4.0

      - run: npm install
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: src-tauri
      - run: npm run tauri build

  cargo-chef:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as it uses the current rustc version as its cache key
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: install webkit2gtk (ubuntu only)
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0

      - name: Cache cargo state
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ubuntu-latest-stable-${{ hashFiles('**/Cargo.toml') }}-
          restore-keys: |
            ubuntu-latest-stable-${{ hashFiles('**/Cargo.toml') }}-
            ubuntu-latest-stable-
            ubuntu-latest-

      # install command to help with cache
      - run: cargo install cargo-chef
      - run: cargo chef prepare --recipe-path recipe.json

      - name: Cache cargo target
        uses: actions/cache@v2
        with:
          path: src-tauri/target
          # Add date to the cache to keep it up to date
          key: ubuntu-latest-stable-${{ hashFiles('recipe.json') }}-
          # Restore from outdated cache for speed
          restore-keys: |
            ubuntu-latest-stable-${{ hashFiles('recipe.json') }}-
            ubuntu-latest-stable-
            ubuntu-latest-

      - run: npm install

      - run: npm run tauri build
