name: testing cache

on:
  push:
    branches:
      - main

jobs:
  rust-cache-action:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1

    # selecting a toolchain either by action or manual `rustup` calls should happen
    # before the plugin, as it uses the current rustc version as its cache key
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: src-tauri
    - run: npm run tauri build
